---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    labels:
      app: mongo
  spec:
    ports:
    - name: mongo
      port: 27017
      targetPort: 27017
    clusterIP: None
    selector:
      app: mongo
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongo
  spec:
    selector:
      matchLabels:
        app: mongo
    serviceName: "mongo"
    replicas: 1
    template:
      metadata:
        labels:
          app: mongo
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: mongo
          # image: mongo
          image: mongo:4.4.18
          command: ["/bin/sh", "-c"]
          args: ["mkdir -p /data/db; mongod --bind_ip_all"]
          # command:
          # - mongod
          # - "--bind_ip_all"
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
        volumes:
        - name: mongo-volume
          hostPath:
            path: /mnt/host
            type: DirectoryOrCreate
